### ISSUE TITLE
Support for python 3

### ISSUE THREAD

**Issue by Mte90** [pleft/omega2-python-evdev#1]
It is possible to port over python 3?

**Comment by pleft** [comment]
Hi, I just cross-compiled the `evdev` 0.4.7-1 version library for omega2. This version as I can remember works with 2.7 python, I am not sure/not tested python3. To have it working on python3 I guess one needs to cross-compile an `evdev` version that works with python3, but that's not something I am intending currently to do. Thanks for asking though!

**Comment by Mte90** [comment]
I started creating a cross compile environment for omega to compile evdev for it.
Do you have any hints in case?

**Comment by pleft** [comment]
Have you checked this? https://github.com/gvalkov/python-evdev/releases
Probably will work on omega2

**Comment by Mte90** [comment]
I did a fork https://github.com/Mte90/omega2-python-evdev
with the new packages updated and also for python3 so if you want you can mark this is as obsoleted in the readme and redirect to that :-)
